name: DeployApp

on:
  push:
    branches: [main]
  pull_request:

run-name: "Deploy Web App"

jobs:
  Deploy:
    concurrency:
      group: project-alpha-deploy
      cancel-in-progress: true
    runs-on: ubuntu-latest
    env:
      working-directory: ./web
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          package_json_file: ./web/package.json

      - name: env
        working-directory: ${{ env.working-directory }}
        run: |
          echo "${{ secrets.ENV_FILE }}" >> .env

      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: |
          pnpm install

      - name: Generate Prisma Client
        run: pnpm prisma generate
        working-directory: ./web

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: pnpm
          preCommands: pnpm build
          command: "pages deploy"
          workingDirectory: ${{ env.working-directory }}
